import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";

import { NavBar, HeaderInformation } from "./components/header";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-inter",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/dheereshag/coloured-icons@1.9.6/app/ci.min.css"
        />
      </head>

      <body className="antialiased min-h-screen text-white">
        <div className="content min-h-screen p-3">
          { NavBar() },
          { HeaderInformation() }
        </div>
      </body>
    </html>
  );
}
